apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.outputapp.service.name }}
spec:
  type: {{ .Values.outputapp.service.type }}
  selector:
    app: {{ .Values.outputapp.labels.app }}
  ports:
    - port: {{ .Values.outputapp.service.ports.port }}
      targetPort: {{ .Values.outputapp.deploy.containers.ports.containerPort }}



